### ISSUE TITLE
Erro no parametro PredictionSource

### ISSUE THREAD

**Issue by JohnVidal77** [otonii/meu-terminal#1]
![image](https://user-images.githubusercontent.com/15021333/116839074-3e6ab200-aba7-11eb-9f70-9d6573846bb2.png)
 Olá,  segui seu tutorial a risca inclusive com a parte de remover o header do powershell, mas aparece esse erro toda vez que inicio o terminal. Não está atrapalhando o uso mas ainda assim seria interessante conseguir resolver isso. Alguma dica do que posso fazer? Vlw

**Comment by jeanpfs** [comment]
Tenho o mesmo problema, rodando esse comando que passou me retornou esse erro

![image](https://user-images.githubusercontent.com/8262794/117029328-eb8f1880-acd4-11eb-8225-537f0da629da.png)

**Comment by otonii** [comment]
Fala @jeanpfs, no caso do seu é pq ele não encontrou o módulo `PSReadLine`. Possivelmente pode ser um bug do instalador automático que ainda não tive tempo de corrigir.

Você pode instalar o módulo manualmente com o comando `Install-Module -Name PSReadLine -Scope CurrentUser -Force`.

**Comment by JohnVidal77** [comment]
> Oi @JohnVidal77, qual a versão do módulo PSReadLine que está instalada na sua maquina? Você pode descobrir utilizando o comando `Get-InstalledModule -Name "PSReadLine"`.

De fato não estava instalado, segui o passa a passo desse [link](https://github.com/PowerShell/PSReadLine)  e deu certo. Vlw!
